# Generated by Django 3.2.4 on 2021-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_banker'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122)),
                ('sender_acc_no', models.CharField(max_length=122)),
                ('Current_balance', models.IntegerField()),
                ('money_deposit', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
